--------------------------------------------------------------------------------
-- Locations
--------------------------------------------------------------------------------
insert into location (location_name)
values ('Barber Surgeon'),
  ('Blacksmith'),
  ('Bone Smith'),
  ('Catarium'),
  ('Chorusseum'),
  ('Crimson Crockery'),
  ('Dark Armory'),
  ('Dragon Armory'),
  ('Exhausted Lantern Hoard'),
  ('Forum'),
  ('Froskrafter'),
  ('Gaming Gazebo'),
  ('Giga Catarium'),
  ('Gormchymist'),
  ('Gormery'),
  ('Keeper of Dreams'),
  ('Kingsmith'),
  ('Lantern Hoard'),
  ('Leather Worker'),
  ('Mask Maker'),
  ('Organ Grinder'),
  ('Outskirts'),
  ('Plumery'),
  ('Sacred Pool'),
  ('Sanguine Extrusion'),
  ('Sense Memory'),
  ('Silk Mill'),
  ('Skinnery'),
  ('Skyreef Sanctuary'),
  ('Stone Circle'),
  ('Stone Circle Hot Zone'),
  ('The Sun'),
  ('Throne'),
  ('Tuskworks'),
  ('Weapon Crafter'),
  ('Wet Resin Crafter'),
  ('Wrought Ironworks');