--------------------------------------------------------------------------------
-- Fighting Arts
--------------------------------------------------------------------------------
insert into fighting_art (fighting_art_name)
values -------------------------------------------------------------------------
  -- Fighting Arts
  ------------------------------------------------------------------------------
  ('Abyssal Sadist'),
  ('Acrobatics'),
  ('Adrenaline'),
  ('Agility Fighter'),
  ('Ambidextrous'),
  ('Armored Fist'),
  ('Backstabber'),
  ('Beginner''s Luck'),
  ('Berzerker'),
  ('Bloodzerker'),
  ('Blotted Out'),
  ('Burning Ambition'),
  ('Burning Focus'),
  ('Carapace of Will'),
  ('Champion''s Rite'),
  ('Chin Dash'),
  ('Clutch Fighter'),
  ('Combo Master'),
  ('Convalescer'),
  ('Crazed'),
  ('Crossarm Block'),
  ('Cross Counter'),
  ('Curse Conductor'),
  ('Dark Manifestation'),
  ('Defender'),
  ('Double Dash'),
  ('Dubious Fare'),
  ('Escape Artist'),
  ('Ethereal Pact'),
  ('Extra Sense'),
  ('Fated Blow'),
  ('Feral Shout'),
  ('Feral Strength'),
  ('First Step'),
  ('Freeclimber'),
  ('Giant''s Blood'),
  ('Glass Mask'),
  ('Harvestman'),
  ('Headliner'),
  ('Heroic'),
  ('Infernal Rythm'),
  ('Infinite Lives'),
  ('Inversion'),
  ('Invigorator'),
  ('Last Man Standing'),
  ('Leader'),
  ('Lure Epilepsy'),
  ('Mammoth Hunting'),
  ('Mighty Strike'),
  ('Monster Claw Style'),
  ('Monster Empathy'),
  ('Orator of Death'),
  ('Otherworldly Luck'),
  ('Phantom Friend'),
  ('Piercer'),
  ('Propulsion Drive'),
  ('Purpose'),
  ('Reframe'),
  ('Regicide'),
  ('Relentless'),
  ('Rolling Gait'),
  ('Ruthless'),
  ('Rythm Chaser'),
  ('Seasoned Hunter'),
  ('Shielderang'),
  ('Sieging Offense'),
  ('Sneak Attack'),
  ('Soaring Advance'),
  ('Soft Landing'),
  ('Stockist'),
  ('Strategist'),
  ('Sword Oath'),
  ('Tenacious'),
  ('Thrill Seeker'),
  ('Timeless Eye'),
  ('Tough'),
  ('Trailblazer'),
  ('Transcended Masochist'),
  ('Trick Attack'),
  ('Tumble'),
  ('Unbreakable'),
  ('Unconscious Fighting'),
  ('Unfroggable'),
  ('Unrelenting'),
  ('Vengance'),
  ('Virtuoso'),
  ('Virtuous'),
  ('Wardrobe Expert');