--------------------------------------------------------------------------------
-- Innovations
--------------------------------------------------------------------------------
insert into innovation (innovation_name)
values ('Accept Darkness'),
  ('Albedo'),
  ('Ammonia'),
  ('Aquarobics'),
  ('Arena'),
  ('Barbaric'),
  ('Bed'),
  ('Bell of Challenge'),
  ('Black Guard Code'),
  ('Bloodletting'),
  ('Bloodline'),
  ('Blood Weaving'),
  ('Bloomery'),
  ('Butchery'),
  ('Cannibalize'),
  ('Character'),
  ('Choreia'),
  ('Clan of Death'),
  ('Collective Toil'),
  ('Cooking'),
  ('Citrinitas'),
  ('Crimson Candy'),
  ('Culling Cuisine'),
  ('Dark Water Research'),
  ('Death Pact'),
  ('Destiny'),
  ('Drafting Table'),
  ('Dragon Speech'),
  ('Dreamless Language'),
  ('Dream Schematics'),
  ('Drums'),
  ('Empire'),
  ('Face Painting'),
  ('Family'),
  ('Filleting Table'),
  ('Fig Sapling'),
  ('Fig Tree'),
  ('Final Fighting Art'),
  ('Forbidden Dance'),
  ('Goth Concealer'),
  ('Goth''s Grave'),
  ('Graves'),
  ('Guidepost'),
  ('Hands of the Sun'),
  ('Heart Flute'),
  ('Holy Hovel'),
  ('Holy Sacrifice'),
  ('Holy Scarification'),
  ('Holy Shrine'),
  ('Hovel'),
  ('Implanted Memories'),
  ('Inner Lantern'),
  ('Language'),
  ('Lantern Oven'),
  ('Legless Ball'),
  ('Lucid Dreams'),
  ('Memento Mori'),
  ('Mere Omens'),
  ('Morgue'),
  ('Nightmare Training'),
  ('Nigredo'),
  ('Nutrition'),
  ('Paint'),
  ('Partnership'),
  ('Petal Spiral'),
  ('Pictograph'),
  ('Pottery'),
  ('Precious Fragments'),
  ('Protect the Young'),
  ('Radiating Orb'),
  ('Records'),
  ('Romantic'),
  ('Round Stone Training'),
  ('Rubedo'),
  ('Sacrifice'),
  ('Saga'),
  ('Sauna Shrine'),
  ('Scarification'),
  ('Scrap Smelting'),
  ('Sculpture'),
  ('Settlement Watch'),
  ('Shadow Dancing'),
  ('Shattered Blade'),
  ('Shrine'),
  ('Silent Dialect'),
  ('Silk-Refining'),
  ('Soda Fountain'),
  ('Song of Concord'),
  ('Song of the Brave'),
  ('Stoic Statue'),
  ('Stone Plate'),
  ('Stone Stairs'),
  ('Storytelling'),
  ('Subterranean Agriculture'),
  ('Sun Language'),
  ('Supreme Cuisine'),
  ('Survival of the Fittest'),
  ('Symposium'),
  ('The Knowledge Worm'),
  ('Toppled Bell'),
  ('Trick Transport'),
  ('Ultimate Weapon'),
  ('Umbilical Bank'),
  ('War Room'),
  ('Water of Life');