--------------------------------------------------------------------------------
-- Patterns
--------------------------------------------------------------------------------
insert into pattern (pattern_name)
values -------------------------------------------------------------------------
  -- Patterns
  ------------------------------------------------------------------------------
  ('Binding Chain'),
  ('Blood Drinker'),
  ('Bone Chibouk'),
  ('Bow Scab'),
  ('Bully Hammer'),
  ('Colossal Chef''s Carver'),
  ('Count Wrappings'),
  ('Count Sandals'),
  ('Count Tabard'),
  ('Count Treukh'),
  ('Count Vest'),
  ('Cruel Cleaver'),
  ('Curse Hammer'),
  ('Dashing Reaper'),
  ('Diamond Scab Katar'),
  ('Discordian'),
  ('Dissecting Celurit'),
  ('Dome Buster'),
  ('Drum of Hope'),
  ('Earl Boots'),
  ('Earl Jaw Guard'),
  ('Earl Raiment'),
  ('Earl Sleeves'),
  ('Earl Tassets'),
  ('Fated Dagger'),
  ('Fear Spear'),
  ('First Tree Cudgel'),
  ('Greatest Gaxe'),
  ('Grimacing Guillotine'),
  ('Grim Muffler'),
  ('Gusk Knife'),
  ('Halberd Scab'),
  ('Holy Sword Whip'),
  ('Horokubiya Dagger'),
  ('Immortal Arm'),
  ('Inquisitorial Saw'),
  ('Jaw Saw'),
  ('Knife Scab'),
  ('Longclaw'),
  ('Lordsruin'),
  ('Mage''s Hood'),
  ('Marchioness Blouse'),
  ('Marchioness Gloves'),
  ('Marchioness Gorget'),
  ('Marchioness Sollerets'),
  ('Marchioness Trousers'),
  ('Maul Scab'),
  ('Oblouk Shield'),
  ('Poison Partisan'),
  ('Regal Plume'),
  ('Regicider'),
  ('Roaring Harmonica'),
  ('Saxe'),
  ('Screaming Sun Mask'),
  ('Screaming Tanto'),
  ('Seditioner'),
  ('Shield of Courage'),
  ('Spiral Mask'),
  ('Stampede Glaive'),
  ('Sunlantern Mask'),
  ('Sword Scab'),
  ('Syncretic Vestments'),
  ('Tachyon Nodachi'),
  ('Thumping Timpani'),
  ('Toxicimitar'),
  ('Tyrant Slayer'),
  ('Unbreakable Zanbato'),
  ('Veteran Lantern Cuirass'),
  ('Violet Armor Charm'),
  ('Violet Phoenix Faulds'),
  ('Violet Phoenix Gauntlets'),
  ('Voluptuous Bodysuit');