--------------------------------------------------------------------------------
-- Seed Patterns
--------------------------------------------------------------------------------
insert into seed_pattern (seed_pattern_name)
values -------------------------------------------------------------------------
  -- Seed Patterns
  ------------------------------------------------------------------------------
  ('Armorsmith''s Tongs'),
  ('Backstabbing Stone'),
  ('Beast Hunter Helm'),
  ('Big Bite Costume'),
  ('Black Ghost Dagger'),
  ('Bloomlink Pumpkin'),
  ('Bravelink Pumpkin'),
  ('Brazen Bat'),
  ('Clasping Shield'),
  ('Cyclops Ledger'),
  ('Death Defier'),
  ('Dextral Crabaxe'),
  ('Dream Keeper Cowl'),
  ('Dream Keeper Knife'),
  ('Elder''s Aegis'),
  ('Feral Zanbato'),
  ('Fingernail Whip'),
  ('Ghostlink Pumpkin'),
  ('Gold Cat Costume'),
  ('Guidon Lance of Doom'),
  ('Heartseeker'),
  ('Hollowlink Pumpkin'),
  ('Hushing Harmonium'),
  ('Hypersight Visor'),
  ('Imitation Butcher Mask'),
  ('Itemsmith''s Lens'),
  ('Jarngreipr'),
  ('Lucky Cat Fang Knife'),
  ('Masamune'),
  ('Master Bone Dagger'),
  ('Mighty Bone Axe'),
  ('Monster Trophy'),
  ('Neko Twilight Armor'),
  ('Ornate Rapier'),
  ('Piercing Claws'),
  ('Plasma Cutter'),
  ('Plated Shield'),
  ('Rawhide Bandana'),
  ('Reaperjaw'),
  ('Refined Lantern Axe'),
  ('Refined Lantern Sword'),
  ('Retching Costume'),
  ('Robes of Deadheim'),
  ('Screaming Costume'),
  ('Scythe of Doom'),
  ('Shadow Skleaver'),
  ('Sinistral Crabaxe'),
  ('Soldier Lantern Cuirass'),
  ('Spinal Sickle'),
  ('Spite Balm'),
  ('Sprinter Helm'),
  ('Sundering Crossbow'),
  ('Sword of Doom'),
  ('Telcric Eye Tac'),
  ('Tempered Axe'),
  ('Tempered Dagger'),
  ('Tempered Spear'),
  ('Tithe Box'),
  ('True Lantern Halberd'),
  ('Vault Key Earrings'),
  ('Vixen Tail'),
  ('Weaponsmith''s Hammer');