--------------------------------------------------------------------------------
-- Fighting Arts
--------------------------------------------------------------------------------
insert into fighting_art (fighting_art_name, secret_fighting_art)
values -------------------------------------------------------------------------
  -- Fighting Arts
  ------------------------------------------------------------------------------
  ('Abyssal Sadist', false),
  ('Acrobatics', false),
  ('Adrenaline', false),
  ('Agility Fighter', false),
  ('Ambidextrous', false),
  ('Armored Fist', false),
  ('Backstabber', false),
  ('Beginner''s Luck', false),
  ('Berzerker', false),
  ('Bloodzerker', false),
  ('Blotted Out', false),
  ('Burning Ambition', false),
  ('Burning Focus', false),
  ('Carapace of Will', false),
  ('Champion''s Rite', false),
  ('Chin Dash', false),
  ('Clutch Fighter', false),
  ('Combo Master', false),
  ('Convalescer', false),
  ('Crazed', false),
  ('Crossarm Block', false),
  ('Cross Counter', false),
  ('Curse Conductor', false),
  ('Dark Manifestation', false),
  ('Defender', false),
  ('Double Dash', false),
  ('Dubious Fare', false),
  ('Escape Artist', false),
  ('Ethereal Pact', false),
  ('Extra Sense', false),
  ('Fated Blow', false),
  ('Feral Shout', false),
  ('Feral Strength', false),
  ('First Step', false),
  ('Freeclimber', false),
  ('Giant''s Blood', false),
  ('Glass Mask', false),
  ('Harvestman', false),
  ('Headliner', false),
  ('Heroic', false),
  ('Infernal Rythm', false),
  ('Infinite Lives', false),
  ('Inversion', false),
  ('Invigorator', false),
  ('Last Man Standing', false),
  ('Leader', false),
  ('Lure Epilepsy', false),
  ('Mammoth Hunting', false),
  ('Mighty Strike', false),
  ('Monster Claw Style', false),
  ('Monster Empathy', false),
  ('Orator of Death', false),
  ('Otherworldly Luck', false),
  ('Phantom Friend', false),
  ('Piercer', false),
  ('Propulsion Drive', false),
  ('Purpose', false),
  ('Reframe', false),
  ('Regicide', false),
  ('Relentless', false),
  ('Rolling Gait', false),
  ('Ruthless', false),
  ('Rythm Chaser', false),
  ('Seasoned Hunter', false),
  ('Shielderang', false),
  ('Sieging Offense', false),
  ('Sneak Attack', false),
  ('Soaring Advance', false),
  ('Soft Landing', false),
  ('Stockist', false),
  ('Strategist', false),
  ('Sword Oath', false),
  ('Tenacious', false),
  ('Thrill Seeker', false),
  ('Timeless Eye', false),
  ('Tough', false),
  ('Trailblazer', false),
  ('Transcended Masochist', false),
  ('Trick Attack', false),
  ('Tumble', false),
  ('Unbreakable', false),
  ('Unconscious Fighting', false),
  ('Unfroggable', false),
  ('Unrelenting', false),
  ('Vengance', false),
  ('Virtuoso', false),
  ('Virtuous', false),
  ('Wardrobe Expert', false),
  ------------------------------------------------------------------------------
  -- Secret Fighting Arts
  ------------------------------------------------------------------------------
  ('Acanthus Doctor', true),
  ('Actualize', true),
  ('Aerial Transfusion', true),
  ('Ageless Apprentice', true),
  ('Altered Destiny', true),
  ('Beast of Caratosis', true),
  ('Beetle Strength', true),
  ('Black Guard Style', true),
  ('Bone Whisperer', true),
  ('Buccal Blood Breathing', true),
  ('Clarity of Darkness', true),
  ('Courtly Screenwriter', true),
  ('Crescent Step', true),
  ('Death Touch', true),
  ('Devil''s Melody', true),
  ('Dreamform', true),
  ('Eternal Will', true),
  ('Fencing', true),
  ('Frozen Star', true),
  ('God of Cheaters', true),
  ('Grace of Dormenatus', true),
  ('Hardheaded', true),
  ('Heart of Olthawartta', true),
  ('Hellfire', true),
  ('Immovable Object', true),
  ('King of a Thousand Battles', true),
  ('King''s Step', true),
  ('Legendary Lungs', true),
  ('Lucernae''s Lantern', true),
  ('Mind Palace', true),
  ('Moonwolf Style', true),
  ('Necromancer', true),
  ('Quadradept', true),
  ('Red Fist', true),
  ('Rousing Wail', true),
  ('Sacred Code', true),
  ('Sad Frogdog Song', true),
  ('Scholar of Death', true),
  ('Silk Surgeon', true),
  ('Story of the Forged', true),
  ('Story of the Forsaker', true),
  ('Story of the Library', true),
  ('Sun Eater', true),
  ('Suppressed Shadow', true),
  ('Swordsman''s Promise', true),
  ('Synchronized Strike', true),
  ('True Blade', true),
  ('Unshackled', true),
  ('Vault Key', true),
  ('Zero Presence', true);