--------------------------------------------------------------------------------
-- Disorders
--------------------------------------------------------------------------------
insert into disorder (disorder_name)
values ('Absent Seizures'),
  ('Aichmophobia'),
  ('Anachronistic'),
  ('Anhedonia'),
  ('Anxiety'),
  ('Apathetic'),
  ('Arithmophilia'),
  ('Atelophobia'),
  ('Battle Drunk'),
  ('Binge Eating'),
  ('Bloodlust'),
  ('Brain Smog'),
  ('Chimeric Delusion'),
  ('Codependent'),
  ('Controlophobia'),
  ('Coprolalia'),
  ('Cowardice'),
  ('Delicious'),
  ('Delirium'),
  ('Destined'),
  ('Directional Dyslexia'),
  ('Dishonorable'),
  ('Durability Delusion'),
  ('Emotionless'),
  ('Enfeebled'),
  ('Eproctophilia'),
  ('Ergophobia'),
  ('Fear of the Dark'),
  ('Flower Addiction'),
  ('Ghostly Beauty'),
  ('Hemophobia'),
  ('Hoarder'),
  ('Honorable'),
  ('Hyperactive'),
  ('Hyperalgesia'),
  ('Hyper-Sensitivity'),
  ('Immortal'),
  ('Indecision'),
  ('Intrepid'),
  ('Maladroit'),
  ('Martyr'),
  ('Megalophobia'),
  ('Monster Panic'),
  ('Motion Sickness'),
  ('Narcissistic'),
  ('Overprotective'),
  ('Pacifist'),
  ('Performance Anxiety'),
  ('Phobophobia'),
  ('Photophilia'),
  ('Post-Traumatic Stress'),
  ('Prey'),
  ('Prima Donna'),
  ('Ptophobia'),
  ('Quixotic'),
  ('Rageholic'),
  ('Revenge'),
  ('Schadenfreude'),
  ('Secretive'),
  ('Seizures'),
  ('Serentiy Delusion'),
  ('Shallow Lungs'),
  ('Somniphobia'),
  ('Spiral Ganglia'),
  ('Squeamish'),
  ('Stage Fright'),
  ('Stark Raving'),
  ('Struggler'),
  ('Subjugated'),
  ('Sun-Drunk'),
  ('Superstitious'),
  ('Tiny Arachnophobia'),
  ('Traumatized'),
  ('Tunnel Vision'),
  ('Unlucky'),
  ('Vermin Obsession'),
  ('Vestiphobia'),
  ('Weak Spot'),
  ('Weltschmerz');