--------------------------------------------------------------------------------
-- Characters
--------------------------------------------------------------------------------
insert into character (character_name)
values ('Disorderly'),
  ('Dream of the Heart'),
  ('Natural Healer'),
  ('Out of Sync'),
  ('Sanctimonious'),
  ('The Adventurer'),
  ('The Ardent'),
  ('The Axe'),
  ('The Berzerker'),
  ('The Bow'),
  ('The Bright Knives'),
  ('The Bright Side'),
  ('The Challenger'),
  ('The Clever'),
  ('The Clumsy'),
  ('The Crabby'),
  ('The Dark'),
  ('The Disinterested'),
  ('The Dying'),
  ('The Fang'),
  ('The Gaiety'),
  ('The Gatherer'),
  ('The Glamorous'),
  ('The Hoarder'),
  ('The Hunger'),
  ('The Impetuous'),
  ('The Last Stand'),
  ('The Lithe'),
  ('The Lonely'),
  ('The Lost Echo'),
  ('The Mad'),
  ('The Magma'),
  ('The Mighty'),
  ('The Parent'),
  ('The Queen'),
  ('The Red Survivor'),
  ('The Savior'),
  ('The Shadow'),
  ('The Spear'),
  ('The Sword'),
  ('The Tough'),
  ('The Unfettered'),
  ('The Unlucky'),
  ('The Versatile'),
  ('The Watched'),
  ('Weapon Master');