--------------------------------------------------------------------------------
-- Patterns
--------------------------------------------------------------------------------
insert into pattern (pattern_name, seed_pattern)
values -------------------------------------------------------------------------
  -- Patterns
  ------------------------------------------------------------------------------
  ('Binding Chain', false),
  ('Blood Drinker', false),
  ('Bone Chibouk', false),
  ('Bow Scab', false),
  ('Bully Hammer', false),
  ('Colossal Chef''s Carver', false),
  ('Count Wrappings', false),
  ('Count Sandals', false),
  ('Count Tabard', false),
  ('Count Treukh', false),
  ('Count Vest', false),
  ('Cruel Cleaver', false),
  ('Curse Hammer', false),
  ('Dashing Reaper', false),
  ('Diamond Scab Katar', false),
  ('Discordian', false),
  ('Dissecting Celurit', false),
  ('Dome Buster', false),
  ('Drum of Hope', false),
  ('Earl Boots', false),
  ('Earl Jaw Guard', false),
  ('Earl Raiment', false),
  ('Earl Sleeves', false),
  ('Earl Tassets', false),
  ('Fated Dagger', false),
  ('Fear Spear', false),
  ('First Tree Cudgel', false),
  ('Greatest Gaxe', false),
  ('Grimacing Guillotine', false),
  ('Grim Muffler', false),
  ('Gusk Knife', false),
  ('Halberd Scab', false),
  ('Holy Sword Whip', false),
  ('Horokubiya Dagger', false),
  ('Immortal Arm', false),
  ('Inquisitorial Saw', false),
  ('Jaw Saw', false),
  ('Knife Scab', false),
  ('Longclaw', false),
  ('Lordsruin', false),
  ('Mage''s Hood', false),
  ('Marchioness Blouse', false),
  ('Marchioness Gloves', false),
  ('Marchioness Gorget', false),
  ('Marchioness Sollerets', false),
  ('Marchioness Trousers', false),
  ('Maul Scab', false),
  ('Oblouk Shield', false),
  ('Poison Partisan', false),
  ('Regal Plume', false),
  ('Regicider', false),
  ('Roaring Harmonica', false),
  ('Saxe', false),
  ('Screaming Sun Mask', false),
  ('Screaming Tanto', false),
  ('Seditioner', false),
  ('Shield of Courage', false),
  ('Spiral Mask', false),
  ('Stampede Glaive', false),
  ('Sunlantern Mask', false),
  ('Sword Scab', false),
  ('Syncretic Vestments', false),
  ('Tachyon Nodachi', false),
  ('Thumping Timpani', false),
  ('Toxicimitar', false),
  ('Tyrant Slayer', false),
  ('Unbreakable Zanbato', false),
  ('Veteran Lantern Cuirass', false),
  ('Violet Armor Charm', false),
  ('Violet Phoenix Faulds', false),
  ('Violet Phoenix Gauntlets', false),
  ('Voluptuous Bodysuit', false),
  ------------------------------------------------------------------------------
  -- Seed Patterns
  ------------------------------------------------------------------------------
  ('Armorsmith''s Tongs', true),
  ('Backstabbing Stone', true),
  ('Beast Hunter Helm', true),
  ('Big Bite Costume', true),
  ('Black Ghost Dagger', true),
  ('Bloomlink Pumpkin', true),
  ('Bravelink Pumpkin', true),
  ('Brazen Bat', true),
  ('Clasping Shield', true),
  ('Cyclops Ledger', true),
  ('Death Defier', true),
  ('Dextral Crabaxe', true),
  ('Dream Keeper Cowl', true),
  ('Dream Keeper Knife', true),
  ('Elder''s Aegis', true),
  ('Feral Zanbato', true),
  ('Fingernail Whip', true),
  ('Ghostlink Pumpkin', true),
  ('Gold Cat Costume', true),
  ('Guidon Lance of Doom', true),
  ('Heartseeker', true),
  ('Hollowlink Pumpkin', true),
  ('Hushing Harmonium', true),
  ('Hypersight Visor', true),
  ('Imitation Butcher Mask', true),
  ('Itemsmith''s Lens', true),
  ('Jarngreipr', true),
  ('Lucky Cat Fang Knife', true),
  ('Masamune', true),
  ('Master Bone Dagger', true),
  ('Mighty Bone Axe', true),
  ('Monster Trophy', true),
  ('Neko Twilight Armor', true),
  ('Ornate Rapier', true),
  ('Piercing Claws', true),
  ('Plasma Cutter', true),
  ('Plated Shield', true),
  ('Rawhide Bandana', true),
  ('Reaperjaw', true),
  ('Refined Lantern Axe', true),
  ('Refined Lantern Sword', true),
  ('Retching Costume', true),
  ('Robes of Deadheim', true),
  ('Screaming Costume', true),
  ('Scythe of Doom', true),
  ('Shadow Skleaver', true),
  ('Sinistral Crabaxe', true),
  ('Soldier Lantern Cuirass', true),
  ('Spinal Sickle', true),
  ('Spite Balm', true),
  ('Sprinter Helm', true),
  ('Sundering Crossbow', true),
  ('Sword of Doom', true),
  ('Telcric Eye Tac', true),
  ('Tempered Axe', true),
  ('Tempered Dagger', true),
  ('Tempered Spear', true),
  ('Tithe Box', true),
  ('True Lantern Halberd', true),
  ('Vault Key Earrings', true),
  ('Vixen Tail', true),
  ('Weaponsmith''s Hammer', true);