--------------------------------------------------------------------------------
-- Traits
--------------------------------------------------------------------------------
insert into trait (trait_name)
values ----
  ('10,000 Teeth'),
  ('Adrenal Adept'),
  ('Ancient Tusks'),
  ('Applause'),
  ('Atomic Vigor - Inert'),
  ('Audience'),
  ('Audio Synthesis'),
  ('Baller'),
  ('Bear Fruit'),
  ('Berserker'),
  ('Berzerker'),
  ('Blacken'),
  ('Blood Secret'),
  ('Blood Soaked'),
  ('Bloom'),
  ('Blue Lens - Closed'),
  ('Blue Lens - Open'),
  ('Boiling Blood'),
  ('Bullish Charge'),
  ('Burrow'),
  ('Curb Stomp'),
  ('Critical Failure'),
  ('Critical Mass - Inert'),
  ('Crooked Step'),
  ('Cunning'),
  ('Current'),
  ('Cyclopean Cruelty'),
  ('Destiny''s Marrow'),
  ('Diabolical'),
  ('Dice Bag'),
  ('Discouraging Presence'),
  ('Divine Prowess'),
  ('Double or Death'),
  ('Double Sphincter'),
  ('Drama Lessons'),
  ('Dreaded Trophies'),
  ('Enchanted Flesh'),
  ('Ensnare'),
  ('Exponential Yield'),
  ('Fast Target'),
  ('Foul Stench'),
  ('Full Stride'),
  ('Frenzied Berserker'),
  ('Frustration'),
  ('Full Power'),
  ('Gambler''s Dice'),
  ('Gaseous Bloat'),
  ('Ghost Geometry'),
  ('Ghost Step'),
  ('Giga Claws'),
  ('Gloom'),
  ('Golden Eyes'),
  ('Gorm''s Den'),
  ('Gormyard'),
  ('Green Lens - Closed'),
  ('Green Lens - Open'),
  ('Gritty Armament'),
  ('Gun Action'),
  ('Half Power'),
  ('Heart of the Woods'),
  ('Heavy Load'),
  ('Heft'),
  ('Hivemind'),
  ('Hollow Earth'),
  ('Hounds'),
  ('Hypermetabolism'),
  ('Immaculate Intuition'),
  ('Immortal Presence'),
  ('Impenetrable Trunk'),
  ('Impossible Eyes'),
  ('Indomitable'),
  ('Inverted'),
  ('Invincible'),
  ('Irradiate'),
  ('Jagged Grotto'),
  ('Keen Eyes'),
  ('King''s Aura'),
  ('King''s Combat'),
  ('King''s New Clothes'),
  ('King''s Presence'),
  ('Lantern Vortex'),
  ('Last Act'),
  ('Leap'),
  ('Legendary Horns'),
  ('Light & Shadow'),
  ('Living Shadows'),
  ('Mad Master'),
  ('Magister Ludi'),
  ('Master''s Presence'),
  ('Materialize'),
  ('Mature'),
  ('Mauler'),
  ('Merciless'),
  ('Monochrome'),
  ('Moving Ground'),
  ('Musth'),
  ('Nightmare Fruit'),
  ('Old Battle Scars'),
  ('Old Blood'),
  ('Out-Fighting'),
  ('Outburst'),
  ('Overtone Singing'),
  ('Perfect Aim'),
  ('Performing Artists'),
  ('Power Forward'),
  ('Prehensile Tail - Inert'),
  ('Prepared Tunnels'),
  ('Quickened'),
  ('Razor Bulbs'),
  ('Red Initiate'),
  ('Red Lens - Closed'),
  ('Red Lens - Open'),
  ('Red Preference'),
  ('Red Secret'),
  ('Reinforcements'),
  ('Scorn'),
  ('Seasoned Duelist'),
  ('Secondary Forge'),
  ('Self-Aware'),
  ('Separation Anxiety'),
  ('Set Roots'),
  ('Shade'),
  ('Shadows of Darkness'),
  ('Sheer Cliffs'),
  ('Short Stride'),
  ('Silent Hymn'),
  ('Singing Whale'),
  ('Smart Cat'),
  ('Smash'),
  ('Smolder'),
  ('Solar Energy'),
  ('Somatic Empathy'),
  ('Song Cards'),
  ('Spark of Joy'),
  ('Spawn'),
  ('Spectral Blast'),
  ('Spiderling Action'),
  ('Spiral Age'),
  ('Spry'),
  ('Sun Dial'),
  ('Tombstone'),
  ('Top of the Food Chain'),
  ('Trample'),
  ('True Ghost Step'),
  ('Twitching Leg Pile'),
  ('Unseen Agony'),
  ('Unsteady'),
  ('Vapor of Nothingness'),
  ('Vibration Damage'),
  ('Vicious'),
  ('Weak Spot'),
  ('Whiplash'),
  ('Witching Cloak'),
  ('Zeal');