--------------------------------------------------------------------------------
-- Secret Fighting Arts
--------------------------------------------------------------------------------
insert into secret_fighting_art (secret_fighting_art_name)
values -------------------------------------------------------------------------
  -- Secret Fighting Arts
  ------------------------------------------------------------------------------
  ('Acanthus Doctor'),
  ('Actualize'),
  ('Aerial Transfusion'),
  ('Ageless Apprentice'),
  ('Altered Destiny'),
  ('Beast of Caratosis'),
  ('Beetle Strength'),
  ('Black Guard Style'),
  ('Bone Whisperer'),
  ('Buccal Blood Breathing'),
  ('Clarity of Darkness'),
  ('Courtly Screenwriter'),
  ('Crescent Step'),
  ('Death Touch'),
  ('Devil''s Melody'),
  ('Dreamform'),
  ('Eternal Will'),
  ('Fencing'),
  ('Frozen Star'),
  ('God of Cheaters'),
  ('Grace of Dormenatus'),
  ('Hardheaded'),
  ('Heart of Olthawartta'),
  ('Hellfire'),
  ('Immovable Object'),
  ('King of a Thousand Battles'),
  ('King''s Step'),
  ('Legendary Lungs'),
  ('Lucernae''s Lantern'),
  ('Mind Palace'),
  ('Moonwolf Style'),
  ('Necromancer'),
  ('Quadradept'),
  ('Red Fist'),
  ('Rousing Wail'),
  ('Sacred Code'),
  ('Sad Frogdog Song'),
  ('Scholar of Death'),
  ('Silk Surgeon'),
  ('Story of the Forged'),
  ('Story of the Forsaker'),
  ('Story of the Library'),
  ('Sun Eater'),
  ('Suppressed Shadow'),
  ('Swordsman''s Promise'),
  ('Synchronized Strike'),
  ('True Blade'),
  ('Unshackled'),
  ('Vault Key'),
  ('Zero Presence');