-- Enable Supabase Realtime for gameplay tables.
-- This allows clients to subscribe to row-level changes via the
-- supabase_realtime publication, powering multi-tab and multiplayer sync.
ALTER PUBLICATION supabase_realtime
ADD TABLE hunt;
ALTER PUBLICATION supabase_realtime
ADD TABLE hunt_ai_deck;
ALTER PUBLICATION supabase_realtime
ADD TABLE hunt_hunt_board;
ALTER PUBLICATION supabase_realtime
ADD TABLE hunt_monster;
ALTER PUBLICATION supabase_realtime
ADD TABLE hunt_survivor;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_collective_cognition_reward;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_gear;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_innovation;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_knowledge;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_location;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_milestone;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_nemesis;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_pattern;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_phase;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_phase_returning_survivor;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_philosophy;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_principle;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_quarry;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_resource;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_seed_pattern;
ALTER PUBLICATION supabase_realtime
ADD TABLE settlement_timeline_year;
ALTER PUBLICATION supabase_realtime
ADD TABLE showdown;
ALTER PUBLICATION supabase_realtime
ADD TABLE showdown_ai_deck;
ALTER PUBLICATION supabase_realtime
ADD TABLE showdown_monster;
ALTER PUBLICATION supabase_realtime
ADD TABLE showdown_survivor;
ALTER PUBLICATION supabase_realtime
ADD TABLE survivor;
ALTER PUBLICATION supabase_realtime
ADD TABLE survivor_cursed_gear;
ALTER PUBLICATION supabase_realtime
ADD TABLE survivor_disorder;
ALTER PUBLICATION supabase_realtime
ADD TABLE survivor_fighting_art;
ALTER PUBLICATION supabase_realtime
ADD TABLE survivor_secret_fighting_art;