name: Lint Codebase

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: write
  packages: read
  pull-requests: write
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Lint Codebase
        id: lint
        uses: oxsecurity/megalinter/flavors/javascript@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
